# Generated by Django 5.0.3 on 2024-03-29 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('grader', '0007_auto_20180812_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='用户名')),
                ('cate', models.BooleanField(default=False, verbose_name='是否学生')),
                ('faculty', models.CharField(blank=True, default='undefine', max_length=20, verbose_name='院系')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='文件名字')),
                ('file_obj', models.FileField(upload_to='files/', verbose_name='文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '相关文件信息表',
                'verbose_name_plural': '相关文件信息表',
                'db_table': 'doc',
            },
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={'verbose_name': '用户提交作文', 'verbose_name_plural': '用户提交作文'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '英文作文题库', 'verbose_name_plural': '英文作文题库'},
        ),
        migrations.AddField(
            model_name='essay',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(max_length=100000, verbose_name='作文内容'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grader.question', verbose_name='作文题号'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='作文得分'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(verbose_name='作文分值'),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_score',
            field=models.IntegerField(verbose_name='最低分'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.TextField(max_length=100000, verbose_name='英文作文题目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='set',
            field=models.IntegerField(unique=True, verbose_name='作文集序号'),
        ),
    ]
