# Generated by Django 5.0.3 on 2024-03-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_commonuser_doc_alter_essay_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='submitter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='grader.commonuser', verbose_name='作文提交者'),
            preserve_default=False,
        ),
    ]
