# Generated by Django 5.0.3 on 2024-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0010_rawessays_alter_essay_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='作文题目')),
                ('content', models.TextField(max_length=100000, verbose_name='作文内容')),
                ('logic_score', models.IntegerField(blank=True, null=True, verbose_name='连贯度')),
                ('topic_score', models.IntegerField(blank=True, null=True, verbose_name='切题度')),
                ('submitter', models.IntegerField(verbose_name='作文提交者')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '用户提交中文作文',
                'verbose_name_plural': '用户提交中文作文',
            },
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={'verbose_name': '用户提交英文作文', 'verbose_name_plural': '用户提交英文作文'},
        ),
    ]
